include /srv/math.avasan.org/current/deploy/nginx/http-maps.conf;

server {
	listen 80;
	listen [::]:80;
	server_name math.avasan.org;

	include /srv/math.avasan.org/current/deploy/nginx/server-policy.conf;
}
