/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CourseAssignmentContent: typeof import('./components/CourseAssignmentContent.vue')['default']
    CourseExplorer: typeof import('./components/CourseExplorer.vue')['default']
    GraphSketcherWorkspace: typeof import('./components/GraphSketcherWorkspace.vue')['default']
    LazyMarkdownContent: typeof import('./components/LazyMarkdownContent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScratchProjectOverlay: typeof import('./components/ScratchProjectOverlay.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
    WorkspaceViewToggle: typeof import('./components/WorkspaceViewToggle.vue')['default']
  }
}
